
set_blocked_apps:
  fields:
    blocked_apps:
      required: True
      example: netflix
    target_profile:
      required: False
      example: John Doe or 1234567
    target_network:
      required: False
      example: My Network or 1234567    

remove_stale_devices:
  fields:
    days:
      required: false
      default: 7
      selector:
        number:
          min: 1
          max: 365
          unit_of_measurement: d
    dry_run:
      required: false
      default: true
      selector:
        boolean:
    remove_unknown:
      required: false
      default: false
      selector:
        boolean:
